spring:
  security:
    oauth2:
      client:
        registration:
          b2c-github:
            provider: b2c-github-provider
            client-id: e7566cce-b60a-422f-9dac-9349c479e028
            client-secret: c5a93004-6855-402f-8498-98327b63d37b
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          b2c-github-provider:
            authorization-uri: https://cestoque.b2clogin.com/cestoque.onmicrosoft.com/b2c_1_cestoque_github/oauth2/v2.0/authorize
            token-uri: https://cestoque.b2clogin.com/cestoque.onmicrosoft.com/b2c_1_cestoque_github/oauth2/v2.0/token
            jwk-set-uri: https://cestoque.b2clogin.com/cestoque.onmicrosoft.com/b2c_1_cestoque_github/discovery/v2.0/keys
